### ISSUE TITLE
Format of the file debate2008.words

### ISSUE THREAD

**Issue by ghost** [vietansegan/sits#1]
Hi, I am trying your code and preprocessing the input file. But I am bit of confused of you example data. There are 3 problems:
(1) As you said, the blank lines in `<dataset>.words` are to separate the conversations. However, there is a blank line at `line 5` of `debate2008.words` while in `dabate.text`, the first blank line is  at `line 157`. Also, the `line 184` and `185` are both blank lines. Why?

(2)According to your explanation in `readme`,  there is  `<num-words-conv-1-turn-T1>\t<word-1> <word-2> ...\n`. what does `T1` mean here? 

(3) Do I need to remove all the stopwords in `.voc`? I can't see common word like `hello` in the dataset. 

Thank you in advance!

**Comment by ezubaric** [comment]
2) T1 means the first turn
3) Yes, you need to remove stopwords

**Comment by ghost** [comment]
@ezubaric  Thanks for reply! But what is the difference between `<num-words-conv-1-turn-1>` and `<num-words-conv-1-turn-T1>`?

**Comment by vietansegan** [comment]
T1 is just to denote the number of turns in conversation 1.

About your first question, line 5 in debate2008.words is not blank; it's just a very short turn which after filtering out OOV words, it's empty. That's why it has the number 0 indicating there is no token in the turn.

Blank line 157 in dabate.text corresponds to line 159 in debate2008.words, which is due to the first 2 lines storing the number of conversations and total number of turns in debate2008.words.

**Comment by ghost** [comment]
@vietansegan  I run the program successfully now! Thanks for your reply!
